<?php $presets["china"] = array (
  'top_bar-show' => '1',
  'top_bar-bg_color' => '#000000',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#707070',
  'top_bar-contact_show' => '1',
  'top_bar-contact_icons_color' => '#686868',
  'top_bar-contact_icons_bg_color' => '#ffffff',
  'top_bar-contact_icons_bg_opacity' => 15,
  'top_bar-contact_address' => '102580 Santa Monica BLVD Los Angeles',
  'top_bar-contact_phone' => '+3 045 224 33 12',
  'top_bar-contact_email' => 'info@yoursite.com',
  'top_bar-contact_skype' => '',
  'top_bar-search_show' => '1',
  'top_bar-search_bg_color' => '#ffffff',
  'top_bar-search_bg_opacity' => 16,
  'top_bar-search_color' => '#707070',
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/china.bottom-bar-logo-regular.png?w=38&h=50',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/china.bottom-bar-logo-hd.png?w=76&h=100',
    1 => 0,
  ),
  'bottom_bar-bg_color' => '#000000',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#707070',
  'bottom_bar-copyrights' => '',
  'bottom_bar-credits' => '1',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 16,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Asul',
  'fonts-h1_font_size' => 40,
  'fonts-h1_line_height' => 50,
  'fonts-h1_uppercase' => '1',
  'fonts-h2_font_family' => 'Asul',
  'fonts-h2_font_size' => 32,
  'fonts-h2_line_height' => 30,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Asul',
  'fonts-h3_font_size' => 22,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Asul',
  'fonts-h4_font_size' => 16,
  'fonts-h4_line_height' => 20,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Asul',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Arial',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 22,
  'fonts-h6_uppercase' => false,
  'buttons-bg_color' => '#c81032',
  'buttons-shadow' => '#8d041d',
  'buttons-text_color' => '#ffffff',
  'buttons-text_shadow' => '#8d041d',
  'buttons-s_font_family' => 'Asul',
  'buttons-s_font_size' => 13,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 25,
  'buttons-m_font_family' => 'Asul',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 31,
  'buttons-l_font_family' => 'Asul',
  'buttons-l_font_size' => 18,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 39,
  'content-headers_color' => '#eeeeee',
  'content-primary_text_color' => '#686868',
  'content-secondary_text_color' => '#eeeeee',
  'content-additional_bg_color' => '#ffffff',
  'content-additional_bg_opacity' => 7,
  'content-additional_bg_ie_color' => '#303030',
  'sidebar-bg_color' => '#131313',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/china.sidebar-bg-image.png',
    'repeat' => 'no-repeat',
    'position_x' => 'right',
    'position_y' => 'top',
  ),
  'sidebar-dividers_color' => '#2d2d2d',
  'sidebar-dividers_opacity' => 86,
  'sidebar-dividers_ie_color' => '#303030',
  'sidebar-headers_color' => '#eeeeee',
  'sidebar-primary_text_color' => '#686868',
  'sidebar-secondary_text_color' => '#eeeeee',
  'footer-bg_color' => '#131313',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/china.footer-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#2d2d2d',
  'footer-dividers_opacity' => 86,
  'footer-dividers_ie_color' => '#303030',
  'footer-headers_color' => '#eeeeee',
  'footer-primary_text_color' => '#686868',
  'footer-secondary_text_color' => '#eeeeee',
  'hoover-color' => '#0c0c0c',
  'hoover-opacity' => 40,
  'hoover-style' => 'none',
  'slideshow-bg_color' => '#8d0b23',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/china.slideshow-bg-image.gif',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => '1',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/china.header-logo-regular.png?w=187&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/china.header-logo-hd.png?w=374&h=160',
    1 => 0,
  ),
  'header-bg_color' => '#131313',
  'header-bg_opacity' => 100,
  'header-bg_ie_color' => '#000000',
  'header-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/china.header-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header_overlapped-bg_color' => '#070707',
  'header_overlapped-bg_opacity' => 50,
  'header_overlapped-bg_ie_color' => '#070707',
  'header_overlapped-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea' => '<p><font color="#c81032">Adress:</font>  102580 Santa Monica BLVD Los Angeles
</p>
<font color="#c81032">Tel: </font> +3 045 224 33 00',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Asul',
  'header-font_size' => 16,
  'header-font_uppercase' => false,
  'header-font_line_height' => 34,
  'header-font_color' => '#ffffff',
  'header-hoover_color' => '#ffffff',
  'header-hoover_bg_color' => '#c81032',
  'header-hoover_bg_opacity' => 100,
  'header-hoover_bg_ie_color' => '#D74340',
  'header-menu_bg_color' => '#070707',
  'header-menu_bg_opacity' => 100,
  'header-menu_bg_ie_color' => '#000000',
  'header-submenu_parent_clickable' => '1',
  'header-submenu_color' => '#1e1e1e',
  'header-submenu_hoover_color' => '#c81032',
  'header-submenu_bg_color' => '#eeeeee',
  'header-submenu_bg_opacity' => 100,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_dividers_color' => '#0c0c0c',
  'header-submenu_dividers_opacity' => 9,
  'header-submenu_dividers_ie_color' => '#d6d6d6',
  'general-bg_color' => '#262626',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#dddddd',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/china.general-boxed-bg-image.gif',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-responsive' => '1',
  'general-hd_images' => '1',
  'general-accent_text_color' => '#ffffff',
  'general-accent_bg_color' => '#c81032',
  'general-next_prev_in_blog' => '1',
  'general-next_prev_in_portfolio' => '1',
  'general-show_author_in_blog' => '1',
  'general-tracking_code' => '',
  'general-favicon' => '',
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-show_rel_projects' => '1',
  'general-rel_projects_head_title' => 'Related projects',
  'general-rel_projects_arrows' => '1',
  'general-rel_projects_max' => 16,
  'general-rel_projects_title' => '1',
  'general-rel_projects_excerpt' => '1',
  'general-rel_projects_link' => '1',
  'general-rel_projects_details' => '1',
  'general-blog_meta_on' => '1',
  'general-blog_meta_postformat' => '1',
  'general-blog_meta_date' => '1',
  'general-blog_meta_author' => '1',
  'general-blog_meta_categories' => '1',
  'general-blog_meta_comments' => '1',
  'general-blog_meta_tags' => '1',
  'general-portfolio_meta_on' => '1',
  'general-portfolio_meta_date' => '1',
  'general-portfolio_meta_author' => false,
  'general-portfolio_meta_categories' => '1',
  'general-portfolio_meta_comments' => '1',
  'stripes-stripe_1_color' => '#262626',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#222526',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#eeeeee',
  'stripes-stripe_1_text_color' => '#686868',
  'stripes-stripe_1_additional_bg_color' => '#ffffff',
  'stripes-stripe_1_additional_bg_opacity' => 6,
  'stripes-stripe_1_additional_bg_ie_color' => '#303030',
  'stripes-stripe_2_color' => '#131313',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#aeaeae',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/china.stripes-stripe-2-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_text_color' => '#828282',
  'stripes-stripe_2_additional_bg_color' => '#242424',
  'stripes-stripe_2_additional_bg_opacity' => 100,
  'stripes-stripe_2_additional_bg_ie_color' => '#dcdcdb',
  'stripes-stripe_3_color' => '#2e2e2e',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#eeeeee',
  'stripes-stripe_3_text_color' => '#707070',
  'stripes-stripe_3_additional_bg_color' => '#242424',
  'stripes-stripe_3_additional_bg_opacity' => 100,
  'stripes-stripe_3_additional_bg_ie_color' => '#dcdcdb',
  'general-thick_divider_style' => 'style-2',
  'general-thin_divider_style' => 'style-1',
  'general-rel_projects_fullwidth_height' => 230,
  'general-rel_projects_height' => 190,
  'content-dividers_color' => '#ffffff',
  'content-dividers_opacity' => 9,
  'content-dividers_ie_color' => '#303030',
  'top_bar-contact_clock' => '',
  'top_bar-contact_info' => '',
  'stripes-stripe_1_bg_fullscreen' => false,
  'stripes-stripe_1_div_color' => '#ffffff',
  'stripes-stripe_1_div_opacity' => 7,
  'stripes-stripe_1_div_ie_color' => '#303030',
  'stripes-stripe_2_bg_fullscreen' => false,
  'stripes-stripe_2_div_color' => '#282828',
  'stripes-stripe_2_div_opacity' => 100,
  'stripes-stripe_2_div_ie_color' => '#61a5bc',
  'stripes-stripe_3_bg_fullscreen' => false,
  'stripes-stripe_3_div_color' => '#222222',
  'stripes-stripe_3_div_opacity' => 100,
  'stripes-stripe_3_div_ie_color' => '#dcdcdb',
  'general-wysiwig_visual_columns' => false,
); ?>