<?php $presets["deep"] = array (
  'top_bar-show' => '1',
  'top_bar-bg_color' => '#252c33',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat-x',
    'position_x' => 'center',
    'position_y' => 'bottom',
  ),
  'top_bar-text_color' => '#8a9199',
  'top_bar-contact_show' => '1',
  'top_bar-contact_icons_color' => '#8a9199',
  'top_bar-contact_icons_bg_color' => '#384450',
  'top_bar-contact_icons_bg_opacity' => 100,
  'top_bar-contact_address' => '102580 Santa Monica BLVD Los Angeles',
  'top_bar-contact_phone' => '+3 045 224 33 12',
  'top_bar-contact_email' => 'info@yoursite.com',
  'top_bar-contact_skype' => '',
  'top_bar-search_show' => '1',
  'top_bar-search_bg_color' => '#384450',
  'top_bar-search_bg_opacity' => 100,
  'top_bar-search_color' => '#8a9199',
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/deep.bottom-bar-logo-regular.png?w=38&h=50',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/deep.bottom-bar-logo-hd.png?w=76&h=100',
    1 => 0,
  ),
  'bottom_bar-bg_color' => '#252c33',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat-x',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#8a9199',
  'bottom_bar-copyrights' => '',
  'bottom_bar-credits' => '1',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 16,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Roboto Condensed',
  'fonts-h1_font_size' => 50,
  'fonts-h1_line_height' => 50,
  'fonts-h1_uppercase' => '1',
  'fonts-h2_font_family' => 'Roboto Condensed',
  'fonts-h2_font_size' => 42,
  'fonts-h2_line_height' => 40,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Roboto',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Roboto',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Roboto',
  'fonts-h5_font_size' => 18,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Arial',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 22,
  'fonts-h6_uppercase' => false,
  'buttons-bg_color' => '#586b7d',
  'buttons-shadow' => '#435260',
  'buttons-text_color' => '#ffffff',
  'buttons-text_shadow' => '#435260',
  'buttons-s_font_family' => 'Roboto Condensed',
  'buttons-s_font_size' => 13,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 24,
  'buttons-m_font_family' => 'Roboto Condensed',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 31,
  'buttons-l_font_family' => 'Roboto Condensed',
  'buttons-l_font_size' => 19,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 40,
  'content-headers_color' => '#323a45',
  'content-primary_text_color' => '#878c92',
  'content-secondary_text_color' => '#323a45',
  'content-additional_bg_color' => '#8e9498',
  'content-additional_bg_opacity' => 12,
  'content-additional_bg_ie_color' => '#ebecec',
  'sidebar-bg_color' => '#f1f1f2',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#f2f3f3',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat-x',
    'position_x' => 'center',
    'position_y' => 'bottom',
  ),
  'sidebar-dividers_color' => '#8e9498',
  'sidebar-dividers_opacity' => 15,
  'sidebar-dividers_ie_color' => '#dedfe1',
  'sidebar-headers_color' => '#323a45',
  'sidebar-primary_text_color' => '#7b8086',
  'sidebar-secondary_text_color' => '#323a45',
  'footer-bg_color' => '#2e3944',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#f2f3f3',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#8e9498',
  'footer-dividers_opacity' => 17,
  'footer-dividers_ie_color' => '#3b454f',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#8a9199',
  'footer-secondary_text_color' => '#ffffff',
  'hoover-color' => '#323a45',
  'hoover-opacity' => 60,
  'hoover-style' => 'none',
  'slideshow-bg_color' => '#2e3944',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#f2f3f3',
  'slideshow-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/deep.slideshow-bg-image.png',
    'repeat' => 'repeat-x',
    'position_x' => 'center',
    'position_y' => 'bottom',
  ),
  'slideshow-bg_fullscreen' => false,
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/deep.header-logo-regular.png?w=187&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/deep.header-logo-hd.png?w=374&h=160',
    1 => 0,
  ),
  'header-bg_color' => '#2e3944',
  'header-bg_opacity' => 100,
  'header-bg_ie_color' => '#000000',
  'header-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/deep.header-bg-image.png',
    'repeat' => 'repeat-x',
    'position_x' => 'center',
    'position_y' => 'bottom',
  ),
  'header_overlapped-bg_color' => '#2e3944',
  'header_overlapped-bg_opacity' => 80,
  'header_overlapped-bg_ie_color' => '#2e3944',
  'header_overlapped-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat-x',
    'position_x' => 'center',
    'position_y' => 'bottom',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea' => '<p><font color="#30bc9c">Adress:</font>  102580 Santa Monica BLVD Los Angeles
</p>
<font color="#30bc9c">Tel: </font> +3 045 224 33 12, 220 30 22',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Roboto',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_line_height' => 37,
  'header-font_color' => '#ffffff',
  'header-hoover_color' => '#ffffff',
  'header-hoover_bg_color' => '#30bc9c',
  'header-hoover_bg_opacity' => 100,
  'header-hoover_bg_ie_color' => '#D74340',
  'header-menu_bg_color' => '#7a8998',
  'header-menu_bg_opacity' => 19,
  'header-menu_bg_ie_color' => '#3c4854',
  'header-submenu_parent_clickable' => '1',
  'header-submenu_color' => '#ffffff',
  'header-submenu_hoover_color' => '#30bc9c',
  'header-submenu_bg_color' => '#232a33',
  'header-submenu_bg_opacity' => 96,
  'header-submenu_bg_ie_color' => '#232a33',
  'header-submenu_dividers_color' => '#3b454f',
  'header-submenu_dividers_opacity' => 92,
  'header-submenu_dividers_ie_color' => '#3b454f',
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#1a1e22',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/deep.general-boxed-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => false,
  'general-responsive' => '1',
  'general-hd_images' => '1',
  'general-accent_text_color' => '#ffffff',
  'general-accent_bg_color' => '#30bc9c',
  'general-next_prev_in_blog' => '1',
  'general-next_prev_in_portfolio' => '1',
  'general-show_author_in_blog' => '1',
  'general-tracking_code' => '',
  'general-favicon' => '',
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-show_rel_projects' => '1',
  'general-rel_projects_head_title' => 'Related projects',
  'general-rel_projects_arrows' => '1',
  'general-rel_projects_max' => 16,
  'general-rel_projects_title' => '1',
  'general-rel_projects_excerpt' => '1',
  'general-rel_projects_link' => '1',
  'general-rel_projects_details' => '1',
  'general-blog_meta_on' => '1',
  'general-blog_meta_postformat' => '1',
  'general-blog_meta_date' => '1',
  'general-blog_meta_author' => '1',
  'general-blog_meta_categories' => '1',
  'general-blog_meta_comments' => '1',
  'general-blog_meta_tags' => '1',
  'general-portfolio_meta_on' => '1',
  'general-portfolio_meta_date' => '1',
  'general-portfolio_meta_author' => false,
  'general-portfolio_meta_categories' => '1',
  'general-portfolio_meta_comments' => '1',
  'stripes-stripe_1_color' => '#ffffff',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#222526',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#323a45',
  'stripes-stripe_1_text_color' => '#878c92',
  'stripes-stripe_1_additional_bg_color' => '#8e9498',
  'stripes-stripe_1_additional_bg_opacity' => 12,
  'stripes-stripe_1_additional_bg_ie_color' => '#f1f1f2',
  'stripes-stripe_2_color' => '#f1f1f2',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#aeaeae',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#323a45',
  'stripes-stripe_2_text_color' => '#7b8086',
  'stripes-stripe_2_additional_bg_color' => '#8e9498',
  'stripes-stripe_2_additional_bg_opacity' => 13,
  'stripes-stripe_2_additional_bg_ie_color' => '#dcddde',
  'stripes-stripe_3_color' => '#2e3944',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#ffffff',
  'stripes-stripe_3_text_color' => '#8a9199',
  'stripes-stripe_3_additional_bg_color' => '#dcdcdb',
  'stripes-stripe_3_additional_bg_opacity' => 8,
  'stripes-stripe_3_additional_bg_ie_color' => '#3b454f',
  'general-thick_divider_style' => 'style-2-1',
  'general-thin_divider_style' => 'style-1',
  'general-rel_projects_fullwidth_height' => 230,
  'general-rel_projects_height' => 190,
  'content-dividers_color' => '#8e9498',
  'content-dividers_opacity' => 14,
  'content-dividers_ie_color' => '#ebecec',
  'top_bar-contact_clock' => '',
  'top_bar-contact_info' => '',
  'stripes-stripe_1_bg_fullscreen' => false,
  'stripes-stripe_1_div_color' => '#8e9498',
  'stripes-stripe_1_div_opacity' => 15,
  'stripes-stripe_1_div_ie_color' => '#f1f1f2',
  'stripes-stripe_2_bg_fullscreen' => false,
  'stripes-stripe_2_div_color' => '#8e9498',
  'stripes-stripe_2_div_opacity' => 17,
  'stripes-stripe_2_div_ie_color' => '#dcddde',
  'stripes-stripe_3_bg_fullscreen' => false,
  'stripes-stripe_3_div_color' => '#dcdcdb',
  'stripes-stripe_3_div_opacity' => 11,
  'stripes-stripe_3_div_ie_color' => '#3b454f',
  'general-wysiwig_visual_columns' => false,
); ?>