<?php $presets["indigo"] = array (
  'top_bar-show' => '1',
  'top_bar-bg_color' => '#000000',
  'top_bar-bg_opacity' => 80,
  'top_bar-bg_ie_color' => '#000000',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#e9f5fa',
  'top_bar-contact_show' => '1',
  'top_bar-contact_icons_color' => '#e9f5fa',
  'top_bar-contact_icons_bg_color' => '#4e718c',
  'top_bar-contact_icons_bg_opacity' => 37,
  'top_bar-contact_address' => '102580 Santa Monica BLVD Los Angeles',
  'top_bar-contact_phone' => '+3 045 224 33 12',
  'top_bar-contact_email' => 'info@yoursite.com',
  'top_bar-contact_skype' => '',
  'top_bar-search_show' => '1',
  'top_bar-search_bg_color' => '#4e718c',
  'top_bar-search_bg_opacity' => 43,
  'top_bar-search_color' => '#e9f5fa',
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/indigo.bottom-bar-logo-regular.png?w=38&h=50',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/indigo.bottom-bar-logo-hd.png?w=76&h=100',
    1 => 0,
  ),
  'bottom_bar-bg_color' => '#000000',
  'bottom_bar-bg_opacity' => 80,
  'bottom_bar-bg_ie_color' => '#000000',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#e9f5fa',
  'bottom_bar-copyrights' => '',
  'bottom_bar-credits' => '1',
  'fonts-font_family' => 'Trebuchet MS',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Fauna One',
  'fonts-h1_font_size' => 40,
  'fonts-h1_line_height' => 50,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Fauna One',
  'fonts-h2_font_size' => 30,
  'fonts-h2_line_height' => 30,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Fauna One',
  'fonts-h3_font_size' => 21,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Fauna One',
  'fonts-h4_font_size' => 16,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Trebuchet MS',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Trebuchet MS',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 22,
  'fonts-h6_uppercase' => false,
  'buttons-bg_color' => '#454c9f',
  'buttons-shadow' => '#323874',
  'buttons-text_color' => '#ffffff',
  'buttons-text_shadow' => '#323874',
  'buttons-s_font_family' => 'Trebuchet MS',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 25,
  'buttons-m_font_family' => 'Fauna One',
  'buttons-m_font_size' => 14,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 32,
  'buttons-l_font_family' => 'Fauna One',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 40,
  'content-headers_color' => '#e9f5fa',
  'content-primary_text_color' => '#90aebe',
  'content-secondary_text_color' => '#e9f5fa',
  'content-additional_bg_color' => '#000000',
  'content-additional_bg_opacity' => 40,
  'content-additional_bg_ie_color' => '#051015',
  'sidebar-bg_color' => '#000000',
  'sidebar-bg_opacity' => 80,
  'sidebar-bg_ie_color' => '#051015',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'sidebar-dividers_color' => '#316787',
  'sidebar-dividers_opacity' => 35,
  'sidebar-dividers_ie_color' => '#1f262a',
  'sidebar-headers_color' => '#e9f5fa',
  'sidebar-primary_text_color' => '#85a2b1',
  'sidebar-secondary_text_color' => '#e9f5fa',
  'footer-bg_color' => '#000000',
  'footer-bg_opacity' => 40,
  'footer-bg_ie_color' => '#08171d',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#316787',
  'footer-dividers_opacity' => 30,
  'footer-dividers_ie_color' => '#253640',
  'footer-headers_color' => '#e9f5fa',
  'footer-primary_text_color' => '#85a2b1',
  'footer-secondary_text_color' => '#e9f5fa',
  'hoover-color' => '#000000',
  'hoover-opacity' => 40,
  'hoover-style' => 'none',
  'slideshow-bg_color' => '#9bd8fd',
  'slideshow-bg_opacity' => 5,
  'slideshow-bg_ie_color' => '#122c37',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => '1',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/indigo.header-logo-regular.png?w=187&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/indigo.header-logo-hd.png?w=374&h=160',
    1 => 0,
  ),
  'header-bg_color' => '#000000',
  'header-bg_opacity' => 40,
  'header-bg_ie_color' => '#08171d',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header_overlapped-bg_color' => '#070707',
  'header_overlapped-bg_opacity' => 40,
  'header_overlapped-bg_ie_color' => '#081218',
  'header_overlapped-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea' => '<p><font color="#059fc5">Adress:</font>  102580 Santa Monica BLVD Los Angeles
</p>
<font color="#059fc5">Tel: </font> +3 045 224 33 12, +3 045 220 22 10',
  'header-contentarea_color' => '#e9f5fa',
  'header-font_family' => 'Fauna One',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_line_height' => 36,
  'header-font_color' => '#e9f5fa',
  'header-hoover_color' => '#ffffff',
  'header-hoover_bg_color' => '#454c9f',
  'header-hoover_bg_opacity' => 100,
  'header-hoover_bg_ie_color' => '#D74340',
  'header-menu_bg_color' => '#323874',
  'header-menu_bg_opacity' => 89,
  'header-menu_bg_ie_color' => '#323874',
  'header-submenu_parent_clickable' => false,
  'header-submenu_color' => '#1e1e1e',
  'header-submenu_hoover_color' => '#565db1',
  'header-submenu_bg_color' => '#e9f5fa',
  'header-submenu_bg_opacity' => 100,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_dividers_color' => '#353f42',
  'header-submenu_dividers_opacity' => 9,
  'header-submenu_dividers_ie_color' => '#d6d6d6',
  'general-bg_color' => '#07212e',
  'general-bg_opacity' => 76,
  'general-bg_ie_color' => '#0e232f',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-layout' => 'boxed',
  'general-boxed_bg_color' => '#274353',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/indigo.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-responsive' => '1',
  'general-hd_images' => '1',
  'general-accent_text_color' => '#ffffff',
  'general-accent_bg_color' => '#059fc5',
  'general-next_prev_in_blog' => '1',
  'general-next_prev_in_portfolio' => '1',
  'general-show_author_in_blog' => '1',
  'general-tracking_code' => '',
  'general-favicon' => '',
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-show_rel_projects' => '1',
  'general-rel_projects_head_title' => 'Related projects',
  'general-rel_projects_arrows' => '1',
  'general-rel_projects_max' => 20,
  'general-rel_projects_title' => '1',
  'general-rel_projects_excerpt' => '1',
  'general-rel_projects_link' => '1',
  'general-rel_projects_details' => '1',
  'general-blog_meta_on' => '1',
  'general-blog_meta_postformat' => '1',
  'general-blog_meta_date' => '1',
  'general-blog_meta_author' => '1',
  'general-blog_meta_categories' => '1',
  'general-blog_meta_comments' => '1',
  'general-blog_meta_tags' => '1',
  'general-portfolio_meta_on' => '1',
  'general-portfolio_meta_date' => '1',
  'general-portfolio_meta_author' => false,
  'general-portfolio_meta_categories' => '1',
  'general-portfolio_meta_comments' => '1',
  'stripes-stripe_1_color' => '#222526',
  'stripes-stripe_1_opacity' => 0,
  'stripes-stripe_1_ie_color' => '#0e232f',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#e9f5fa',
  'stripes-stripe_1_text_color' => '#90aebe',
  'stripes-stripe_1_additional_bg_color' => '#000000',
  'stripes-stripe_1_additional_bg_opacity' => 40,
  'stripes-stripe_1_additional_bg_ie_color' => '#09181f',
  'stripes-stripe_2_color' => '#000000',
  'stripes-stripe_2_opacity' => 80,
  'stripes-stripe_2_ie_color' => '#051015',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#e9f5fa',
  'stripes-stripe_2_text_color' => '#85a2b1',
  'stripes-stripe_2_additional_bg_color' => '#316787',
  'stripes-stripe_2_additional_bg_opacity' => 30,
  'stripes-stripe_2_additional_bg_ie_color' => '#152228',
  'stripes-stripe_3_color' => '#000000',
  'stripes-stripe_3_opacity' => 40,
  'stripes-stripe_3_ie_color' => '#09181f',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#e9f5fa',
  'stripes-stripe_3_text_color' => '#85a2b1',
  'stripes-stripe_3_additional_bg_color' => '#316787',
  'stripes-stripe_3_additional_bg_opacity' => 20,
  'stripes-stripe_3_additional_bg_ie_color' => '#1d2d36',
  'general-thick_divider_style' => 'style-2',
  'general-thin_divider_style' => 'style-1',
  'general-rel_projects_fullwidth_height' => 230,
  'general-rel_projects_height' => 190,
  'content-dividers_color' => '#000000',
  'content-dividers_opacity' => 47,
  'content-dividers_ie_color' => '#051015',
  'top_bar-contact_clock' => '',
  'top_bar-contact_info' => '',
  'stripes-stripe_1_bg_fullscreen' => false,
  'stripes-stripe_1_div_color' => '#000000',
  'stripes-stripe_1_div_opacity' => 47,
  'stripes-stripe_1_div_ie_color' => '#09181f',
  'stripes-stripe_2_bg_fullscreen' => false,
  'stripes-stripe_2_div_color' => '#316787',
  'stripes-stripe_2_div_opacity' => 35,
  'stripes-stripe_2_div_ie_color' => '#1b2830',
  'stripes-stripe_3_bg_fullscreen' => false,
  'stripes-stripe_3_div_color' => '#316787',
  'stripes-stripe_3_div_opacity' => 30,
  'stripes-stripe_3_div_ie_color' => '#253640',
  'general-wysiwig_visual_columns' => false,
); ?>