<?php $presets["organic"] = array (
  'top_bar-show' => '1',
  'top_bar-bg_color' => '#000000',
  'top_bar-bg_opacity' => 90,
  'top_bar-bg_ie_color' => '#0e0f06',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#ebebe5',
  'top_bar-contact_show' => '1',
  'top_bar-contact_icons_color' => '#ebebe5',
  'top_bar-contact_icons_bg_color' => '#fcf7d1',
  'top_bar-contact_icons_bg_opacity' => 15,
  'top_bar-contact_address' => '102580 Santa Monica BLVD Los Angeles',
  'top_bar-contact_phone' => '+3 045 224 33 12',
  'top_bar-contact_email' => 'info@yoursite.com',
  'top_bar-contact_skype' => '',
  'top_bar-search_show' => '1',
  'top_bar-search_bg_color' => '#fcf7d1',
  'top_bar-search_bg_opacity' => 17,
  'top_bar-search_color' => '#ebebe5',
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/organic.bottom-bar-logo-regular.png?w=38&h=50',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/organic.bottom-bar-logo-hd.png?w=76&h=100',
    1 => 0,
  ),
  'bottom_bar-bg_color' => '#000000',
  'bottom_bar-bg_opacity' => 90,
  'bottom_bar-bg_ie_color' => '#0e0f06',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#ebebe5',
  'bottom_bar-copyrights' => '',
  'bottom_bar-credits' => '1',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 16,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Sanchez',
  'fonts-h1_font_size' => 44,
  'fonts-h1_line_height' => 50,
  'fonts-h1_uppercase' => '1',
  'fonts-h2_font_family' => 'Sanchez',
  'fonts-h2_font_size' => 36,
  'fonts-h2_line_height' => 30,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Sanchez',
  'fonts-h3_font_size' => 23,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Sanchez',
  'fonts-h4_font_size' => 17,
  'fonts-h4_line_height' => 20,
  'fonts-h4_uppercase' => '1',
  'fonts-h5_font_family' => 'Sanchez',
  'fonts-h5_font_size' => 17,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Arial',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 22,
  'fonts-h6_uppercase' => '1',
  'buttons-bg_color' => '#4ab661',
  'buttons-shadow' => '#378849',
  'buttons-text_color' => '#ffffff',
  'buttons-text_shadow' => '#378849',
  'buttons-s_font_family' => 'Lato',
  'buttons-s_font_size' => 13,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 24,
  'buttons-m_font_family' => 'Lato',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 31,
  'buttons-l_font_family' => 'Lato',
  'buttons-l_font_size' => 18,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 38,
  'content-headers_color' => '#323328',
  'content-primary_text_color' => '#67675e',
  'content-secondary_text_color' => '#242421',
  'content-additional_bg_color' => '#fdfdf7',
  'content-additional_bg_opacity' => 100,
  'content-additional_bg_ie_color' => '#dcdcdb',
  'sidebar-bg_color' => '#fdfdf7',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#7f7f7f',
  'sidebar-dividers_opacity' => 14,
  'sidebar-dividers_ie_color' => '#ecece7',
  'sidebar-headers_color' => '#323328',
  'sidebar-primary_text_color' => '#67675e',
  'sidebar-secondary_text_color' => '#4ab661',
  'footer-bg_color' => '#16160e',
  'footer-bg_opacity' => 85,
  'footer-bg_ie_color' => '#33352a',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#878777',
  'footer-dividers_opacity' => 24,
  'footer-dividers_ie_color' => '#49493d',
  'footer-headers_color' => '#fdfdf7',
  'footer-primary_text_color' => '#909089',
  'footer-secondary_text_color' => '#fdfdf7',
  'hoover-color' => '#000000',
  'hoover-opacity' => 40,
  'hoover-style' => 'none',
  'slideshow-bg_color' => '#00a623',
  'slideshow-bg_opacity' => 50,
  'slideshow-bg_ie_color' => '#53c36b',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => '1',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/organic.header-logo-regular.png?w=187&h=80',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/organic.header-logo-hd.png?w=374&h=160',
    1 => 0,
  ),
  'header-bg_color' => '#16160e',
  'header-bg_opacity' => 85,
  'header-bg_ie_color' => '#1d1d18',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header_overlapped-bg_color' => '#16160e',
  'header_overlapped-bg_opacity' => 50,
  'header_overlapped-bg_ie_color' => '#33352a',
  'header_overlapped-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea' => '<p><font color="#4ab661">Adress:</font>  5 First St, NewYork, CA 94103, USA
</p>
<font color="#4ab661">Tel: </font> +3 045 224 33 12, 220 30 22',
  'header-contentarea_color' => '#fdfdf7',
  'header-font_family' => 'Sanchez',
  'header-font_size' => 16,
  'header-font_uppercase' => false,
  'header-font_line_height' => 35,
  'header-font_color' => '#fdfdf7',
  'header-hoover_color' => '#ffffff',
  'header-hoover_bg_color' => '#4ab661',
  'header-hoover_bg_opacity' => 100,
  'header-hoover_bg_ie_color' => '#D74340',
  'header-menu_bg_color' => '#337e44',
  'header-menu_bg_opacity' => 100,
  'header-menu_bg_ie_color' => '#373a3b',
  'header-submenu_parent_clickable' => '1',
  'header-submenu_color' => '#67675e',
  'header-submenu_hoover_color' => '#4ab661',
  'header-submenu_bg_color' => '#fdfdf7',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#fdfdf7',
  'header-submenu_dividers_color' => '#7f7f7f',
  'header-submenu_dividers_opacity' => 12,
  'header-submenu_dividers_ie_color' => '#f0f0eb',
  'general-bg_color' => '#f9f9f3',
  'general-bg_opacity' => 60,
  'general-bg_ie_color' => '#f0f5d3',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => '1',
  'general-layout' => 'boxed',
  'general-boxed_bg_color' => '#f6f4bf',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/organic.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-responsive' => '1',
  'general-hd_images' => '1',
  'general-accent_text_color' => '#ffffff',
  'general-accent_bg_color' => '#4ab661',
  'general-next_prev_in_blog' => '1',
  'general-next_prev_in_portfolio' => '1',
  'general-show_author_in_blog' => '1',
  'general-tracking_code' => '',
  'general-favicon' => '',
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => '6',
  'general-show_rel_projects' => '1',
  'general-rel_projects_head_title' => 'Related projects',
  'general-rel_projects_arrows' => '1',
  'general-rel_projects_max' => '12',
  'general-rel_projects_title' => '1',
  'general-rel_projects_excerpt' => '1',
  'general-rel_projects_link' => '1',
  'general-rel_projects_details' => '1',
  'general-blog_meta_on' => '1',
  'general-blog_meta_postformat' => '1',
  'general-blog_meta_date' => '1',
  'general-blog_meta_author' => '1',
  'general-blog_meta_categories' => '1',
  'general-blog_meta_comments' => '1',
  'general-blog_meta_tags' => '1',
  'general-portfolio_meta_on' => '1',
  'general-portfolio_meta_date' => '1',
  'general-portfolio_meta_author' => '1',
  'general-portfolio_meta_categories' => '1',
  'general-portfolio_meta_comments' => '1',
  'stripes-stripe_1_color' => '#fdfdf7',
  'stripes-stripe_1_opacity' => 0,
  'stripes-stripe_1_ie_color' => '#f6f4bf',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#323328',
  'stripes-stripe_1_text_color' => '#67675e',
  'stripes-stripe_1_additional_bg_color' => '#fdfdf7',
  'stripes-stripe_1_additional_bg_opacity' => 100,
  'stripes-stripe_1_additional_bg_ie_color' => '#fdfdf7',
  'stripes-stripe_2_color' => '#16160e',
  'stripes-stripe_2_opacity' => 85,
  'stripes-stripe_2_ie_color' => '#35352a',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_text_color' => '#828282',
  'stripes-stripe_2_additional_bg_color' => '#878777',
  'stripes-stripe_2_additional_bg_opacity' => 20,
  'stripes-stripe_2_additional_bg_ie_color' => '#45453a',
  'stripes-stripe_3_color' => '#fdfdf7',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#fdfdf7',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#323328',
  'stripes-stripe_3_text_color' => '#67675e',
  'stripes-stripe_3_additional_bg_color' => '#7f7f7f',
  'stripes-stripe_3_additional_bg_opacity' => 10,
  'stripes-stripe_3_additional_bg_ie_color' => '#f0f0eb',
  'general-thick_divider_style' => 'style-2',
  'general-thin_divider_style' => 'style-1',
  'general-rel_projects_fullwidth_height' => '270',
  'general-rel_projects_height' => '190',
  'content-dividers_color' => '#fdfdf7',
  'content-dividers_opacity' => 100,
  'content-dividers_ie_color' => '#e7e7e7',
  'top_bar-contact_clock' => '',
  'top_bar-contact_info' => '',
  'stripes-stripe_1_bg_fullscreen' => false,
  'stripes-stripe_1_div_color' => '#fdfdf7',
  'stripes-stripe_1_div_opacity' => 100,
  'stripes-stripe_1_div_ie_color' => '#fdfdf7',
  'stripes-stripe_2_bg_fullscreen' => false,
  'stripes-stripe_2_div_color' => '#878777',
  'stripes-stripe_2_div_opacity' => 24,
  'stripes-stripe_2_div_ie_color' => '#45453a',
  'stripes-stripe_3_bg_fullscreen' => false,
  'stripes-stripe_3_div_color' => '#7f7f7f',
  'stripes-stripe_3_div_opacity' => 13,
  'stripes-stripe_3_div_ie_color' => '#ecece7',
  'general-wysiwig_visual_columns' => false,
); ?>