<?php $presets["red"] = array (
  'top_bar-show' => '1',
  'top_bar-bg_color' => '#ffffff',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#6f7172',
  'top_bar-contact_show' => '1',
  'top_bar-contact_icons_color' => '#ffffff',
  'top_bar-contact_icons_bg_color' => '#dddddd',
  'top_bar-contact_icons_bg_opacity' => 86,
  'top_bar-contact_address' => '102580 Santa Monica BLVD Los Angeles',
  'top_bar-contact_phone' => '+3 045 224 33 12',
  'top_bar-contact_email' => 'info@yoursite.com',
  'top_bar-contact_skype' => '',
  'top_bar-search_show' => '1',
  'top_bar-search_bg_color' => '#dddddd',
  'top_bar-search_bg_opacity' => 88,
  'top_bar-search_color' => '#6f7172',
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/red.bottom-bar-logo-regular.png?w=38&h=48',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/red.bottom-bar-logo-hd.png?w=76&h=96',
    1 => 0,
  ),
  'bottom_bar-bg_color' => '#ffffff',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#6f7172',
  'bottom_bar-copyrights' => '',
  'bottom_bar-credits' => '1',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 16,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Lato:700',
  'fonts-h1_font_size' => 50,
  'fonts-h1_line_height' => 56,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Lato:700',
  'fonts-h2_font_size' => 34,
  'fonts-h2_line_height' => 40,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Lato:700',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Lato:700',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 22,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Lato:700',
  'fonts-h5_font_size' => 18,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Arial',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 22,
  'fonts-h6_uppercase' => false,
  'buttons-bg_color' => '#d64a4a',
  'buttons-shadow' => '#9a3c3c',
  'buttons-text_color' => '#ffffff',
  'buttons-text_shadow' => '#9a3c3c',
  'buttons-s_font_family' => 'Lato',
  'buttons-s_font_size' => 13,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 24,
  'buttons-m_font_family' => 'Lato:700',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 31,
  'buttons-l_font_family' => 'Lato:700',
  'buttons-l_font_size' => 19,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 40,
  'content-headers_color' => '#2e3031',
  'content-primary_text_color' => '#7f8182',
  'content-secondary_text_color' => '#2e3031',
  'content-additional_bg_color' => '#dddddd',
  'content-additional_bg_opacity' => 67,
  'content-additional_bg_ie_color' => '#dcdcdb',
  'sidebar-bg_color' => '#ffffff',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#dddddd',
  'sidebar-dividers_opacity' => 50,
  'sidebar-dividers_ie_color' => '#ececec',
  'sidebar-headers_color' => '#2e3031',
  'sidebar-primary_text_color' => '#848687',
  'sidebar-secondary_text_color' => '#cf5c5c',
  'footer-bg_color' => '#2e3031',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/red.footer-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#424445',
  'footer-dividers_opacity' => 100,
  'footer-dividers_ie_color' => '#4c4c4c',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#919191',
  'footer-secondary_text_color' => '#ffffff',
  'hoover-color' => '#000000',
  'hoover-opacity' => 30,
  'hoover-style' => 'none',
  'slideshow-bg_color' => '#cb4848',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/red.slideshow-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/red.header-logo-regular.png?w=189&h=79',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/red.header-logo-hd.png?w=378&h=158',
    1 => 0,
  ),
  'header-bg_color' => '#2e3031',
  'header-bg_opacity' => 100,
  'header-bg_ie_color' => '#000000',
  'header-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/red.header-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header_overlapped-bg_color' => '#000000',
  'header_overlapped-bg_opacity' => 30,
  'header_overlapped-bg_ie_color' => '#232526',
  'header_overlapped-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea' => '<p><font color="#7c7c7c">Adress:</font>  102580 Santa Monica BLVD Los Angeles
</p>
<font color="#7c7c7c">Tel: </font> +3 045 224 33 12, 220 30 22',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Lato:700',
  'header-font_size' => 15,
  'header-font_uppercase' => '1',
  'header-font_line_height' => 34,
  'header-font_color' => '#ffffff',
  'header-hoover_color' => '#ffffff',
  'header-hoover_bg_color' => '#d64a4a',
  'header-hoover_bg_opacity' => 100,
  'header-hoover_bg_ie_color' => '#D74340',
  'header-menu_bg_color' => '#000000',
  'header-menu_bg_opacity' => 30,
  'header-menu_bg_ie_color' => '#000000',
  'header-submenu_parent_clickable' => '1',
  'header-submenu_color' => '#6f7172',
  'header-submenu_hoover_color' => '#ca5252',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_dividers_color' => '#eaeaea',
  'header-submenu_dividers_opacity' => 100,
  'header-submenu_dividers_ie_color' => '#ffffff',
  'general-bg_color' => '#f3f3f3',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-layout' => 'wide',
  'general-boxed_bg_color' => '#f5f5f5',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/red.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-responsive' => '1',
  'general-hd_images' => '1',
  'general-accent_text_color' => '#ffffff',
  'general-accent_bg_color' => '#d64a4a',
  'general-next_prev_in_blog' => '1',
  'general-next_prev_in_portfolio' => '1',
  'general-show_author_in_blog' => '1',
  'general-tracking_code' => '',
  'general-favicon' => '',
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => '6',
  'general-show_rel_projects' => '1',
  'general-rel_projects_head_title' => 'Related projects',
  'general-rel_projects_arrows' => '1',
  'general-rel_projects_max' => '16',
  'general-rel_projects_title' => '1',
  'general-rel_projects_excerpt' => '1',
  'general-rel_projects_link' => '1',
  'general-rel_projects_details' => '1',
  'general-blog_meta_on' => '1',
  'general-blog_meta_postformat' => '1',
  'general-blog_meta_date' => '1',
  'general-blog_meta_author' => '1',
  'general-blog_meta_categories' => '1',
  'general-blog_meta_comments' => '1',
  'general-blog_meta_tags' => '1',
  'general-portfolio_meta_on' => '1',
  'general-portfolio_meta_date' => '1',
  'general-portfolio_meta_author' => false,
  'general-portfolio_meta_categories' => '1',
  'general-portfolio_meta_comments' => '1',
  'stripes-stripe_1_color' => '#ffffff',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#222526',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#2e3031',
  'stripes-stripe_1_text_color' => '#848687',
  'stripes-stripe_1_additional_bg_color' => '#dddddd',
  'stripes-stripe_1_additional_bg_opacity' => 45,
  'stripes-stripe_1_additional_bg_ie_color' => '#dcdcdb',
  'stripes-stripe_2_color' => '#2e3031',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#aeaeae',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/red.stripes-stripe-2-bg-image.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_text_color' => '#919191',
  'stripes-stripe_2_additional_bg_color' => '#3b3c3d',
  'stripes-stripe_2_additional_bg_opacity' => 100,
  'stripes-stripe_2_additional_bg_ie_color' => '#dcdcdb',
  'stripes-stripe_3_color' => '#f3f3f3',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#2e3031',
  'stripes-stripe_3_text_color' => '#7f8182',
  'stripes-stripe_3_additional_bg_color' => '#dddddd',
  'stripes-stripe_3_additional_bg_opacity' => 67,
  'stripes-stripe_3_additional_bg_ie_color' => '#e5e5e5',
  'general-thick_divider_style' => 'style-2',
  'general-thin_divider_style' => 'style-1',
  'general-rel_projects_fullwidth_height' => '230',
  'general-rel_projects_height' => '190',
  'content-dividers_color' => '#dddddd',
  'content-dividers_opacity' => 85,
  'content-dividers_ie_color' => '#e5e5e5',
  'top_bar-contact_clock' => '',
  'top_bar-contact_info' => '',
  'stripes-stripe_1_bg_fullscreen' => false,
  'stripes-stripe_1_div_color' => '#dddddd',
  'stripes-stripe_1_div_opacity' => 60,
  'stripes-stripe_1_div_ie_color' => '#e5e5e5',
  'stripes-stripe_2_bg_fullscreen' => false,
  'stripes-stripe_2_div_color' => '#424445',
  'stripes-stripe_2_div_opacity' => 100,
  'stripes-stripe_2_div_ie_color' => '#e5e5e5',
  'stripes-stripe_3_bg_fullscreen' => false,
  'stripes-stripe_3_div_color' => '#dddddd',
  'stripes-stripe_3_div_opacity' => 89,
  'stripes-stripe_3_div_ie_color' => '#e5e5e5',
  'general-wysiwig_visual_columns' => false,
); ?>